# Generated by Django 5.1 on 2024-08-11 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Группу",
                "verbose_name_plural": "Группа",
                "db_table": "Groups",
            },
        ),
        migrations.CreateModel(
            name="Pills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("image", models.ImageField(upload_to="")),
                ("container", models.IntegerField()),
            ],
            options={
                "verbose_name": "Таблетку",
                "verbose_name_plural": "Таблетка",
                "db_table": "Pills",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_taking", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
                "db_table": "Shedule",
            },
        ),
        migrations.CreateModel(
            name="TakingPills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("quantity_pills", models.IntegerField()),
                ("quantity_days", models.IntegerField()),
            ],
            options={
                "verbose_name": "Прием таблеток",
                "verbose_name_plural": "Прием таблеток",
                "db_table": "TekingPills",
            },
        ),
        migrations.CreateModel(
            name="Voices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice1", models.FileField(blank=True, null=True, upload_to="")),
                ("voice2", models.FileField(blank=True, null=True, upload_to="")),
                ("voice3", models.FileField(blank=True, null=True, upload_to="")),
                ("voice4", models.FileField(blank=True, null=True, upload_to="")),
                ("voice5", models.FileField(blank=True, null=True, upload_to="")),
                ("voice6", models.FileField(blank=True, null=True, upload_to="")),
                ("voice7", models.FileField(blank=True, null=True, upload_to="")),
                ("voice8", models.FileField(blank=True, null=True, upload_to="")),
                ("voice9", models.FileField(blank=True, null=True, upload_to="")),
                ("voice10", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Звуки",
                "verbose_name_plural": "Звук",
                "db_table": "Voices",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("username", models.CharField(max_length=256)),
                ("fingerprint", models.PositiveIntegerField()),
                ("portion_of_water", models.CharField(max_length=256)),
                ("number", models.CharField(default="+79000000000", max_length=256)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "groups",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="patients.groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациента",
                "verbose_name_plural": "Пациенты",
                "db_table": "Patients",
            },
        ),
    ]
