# Generated by Django 5.1 on 2024-08-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.patient"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="pills",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.pills"
            ),
        ),
        migrations.AddField(
            model_name="takingpills",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.schedule"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="voices",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.voices"
            ),
        ),
    ]
